<?php
include('header.php');
?>
<h2>STUDENTEN</h2>
<table class="table table-hover table-bordered table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Voornaam</th>
            <th>Achternaam</th>
            <th>Leeftijd</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Daan</td>
            <td>Swart</td>
            <td>31</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Ken</td>
            <td>Sherry</td>
            <td>21</td>
        </tr>
    </tbody>
</table>
<?php
include('footer.php');
?>